### ISSUE TITLE
Only one window should be opened at the same time

### ISSUE THREAD

**Issue by harshil21** [tmslads/Shanisirmodule#15]
The program should be able to detect if say, soundboard window is already open and then switch its focus to it, instead of opening new windows again and again.

**Comment by unclesam79** [comment]
Hmmm very interesting let's see what we can do

**Comment by harshil21** [comment]
partially fixed, still does not work (i.e. does not 'lift' window) when soundboard is minimized and then soundboard button is pressed in shaniUI.

But works when alt-tabbed to shaniUI (when in fullscreen in soundboard)
